# Generated by Django 2.1 on 2019-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='numcomment',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True),
        ),
    ]
