# Generated by Django 2.1 on 2019-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='scores',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2),
        ),
    ]
