# Generated by Django 2.2.6 on 2019-11-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191112_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemslist',
            name='release_year',
        ),
    ]
