# Generated by Django 2.1 on 2019-12-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191112_2152'),
        ('posts', '0002_remove_itemslist_release_year'),
        ('posts', '0003_remove_itemslist_release_year'),
        ('posts', '0005_auto_20191002_0406'),
        ('posts', '0004_auto_20191114_0257'),
    ]

    operations = [
    ]
